export const ASSET_CLASS_ORDER = ['Equities', 'Macro', 'Credit'];
export const TOGGLE_SORT = 'TOGGLE_SORT';
export const SET_DATA = 'SET_DATA';
export const ASSET_CLASS = 'assetClass';
export const PRICE = 'price';
export const TICKER = 'ticker';
export const ASC = 'asc';
export const DESC = 'desc';
export const NONE = 'none';